heart_health/urls.py
from django.urls import path

from . import views

app_name = 'heart_health'
urlpatterns = [
    #path('', views.IndexView.as_view(), name='index'),
    path('', views.index, name='index'),
    path('survey', views.survey, name='survey'),
    path('outcome', views.outcome, name='outcome'),
    path('education', views.education, name='education'),
    #path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote')

]

heart_health_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('heart_health/', include('heart_health.urls')),
    path('admin/', admin.site.urls),
]

heart_health/forms.py
from random import choices
from turtle import width, window_height
from django import forms
from django.forms.widgets import NumberInput, RadioSelect, TextInput
from django.forms import TextInput, RadioSelect



class SurveyForm(forms.Form):
    '''
    Creates the Django form. Each field is customized to only allow the values that make sense for validation purposes. 
    '''
    
    name = forms.CharField(label='Name', max_length = 30, widget=forms.TextInput(attrs={'placeholder': 'Name', 'style': 'width: 300px', 'class': 'form-control'}))
    
    sex_choices = [("male", "Male"), ("female", "Female")]
    sex = forms.ChoiceField(label='Sex', choices=sex_choices, widget = forms.RadioSelect(attrs = {"class": "inline"}))
    
    birth_date = forms.DateField(widget=NumberInput(attrs={'type': 'date', 'style': 'height: 30px'}))

    height = forms.FloatField(help_text = "feet", min_value=4, max_value=7, widget=forms.NumberInput(attrs={'placeholder': 'Ex: 5.4', 'class': 'form-control', 'step': "0.1", 'style': 'width : 100px; height: 30px'}))

    weight = forms.IntegerField(help_text = "lbs", min_value=75, max_value=400, widget=forms.NumberInput(attrs={'class': 'form-control','style': 'width : 100px; height: 30px'}))

    sys_bp = forms.IntegerField(label='Systolic Blood Pressure', help_text = "mmHg", min_value=60, max_value=220,
             widget=forms.NumberInput(attrs={'placeholder': 'Normal is ~120', 'class': 'form-control','style': 'width : 120px; height: 30px'}))

    state_list = [('Alabama', 'Alabama'), ('Alaska', 'Alaska'), ('Arizona', 'Arizona'),
                ('Arkansas', 'Arkansas'), ('California', 'California'), ('Colorado', 'Colorado'),
                ('Connecticut', 'Connecticut'), ('Delaware', 'Delaware'), ('Florida', 'Florida'),
                ('Georgia', 'Georgia'), ('Hawaii', 'Hawaii'), ('Idaho', 'Idaho'), ('Illinois', 'Illinois'),
                ('Indiana', 'Indiana'), ('Iowa', 'Iowa'), ('Kansas', 'Kansas'), ('Kentucky', 'Kentucky'),
                ('Louisiana', 'Louisiana'), ('Maine', 'Maine'), ('Maryland', 'Maryland'), ('Massachusetts', 'Massachusetts'),
                ('Michigan', 'Michigan'), ('Minnesota', 'Minnesota'), ('Mississippi', 'Mississippi'), ('Missouri', 'Missouri'),
                ('Montana', 'Montana'), ('Nebraska', 'Nebraska'), ('Nevada', 'Nevada'), ('New_Hampshire', 'New Hampshire'), 
                ('New_Jersey', 'New Jersey'), ('New_Mexico', 'New Mexico'), ('New_York', 'New York'), ('North_Carolina', 'North Carolina'),
                ('North_Dakota', 'North Dakota'), ('Ohio', 'Ohio'), ('Oklahoma', 'Oklahoma'), ('Oregon', 'Oregon'),
                ('Pennsylvania', 'Pennsylvania'), ('Rhode_Island', 'Rhode Island'), ('South_Carolina', 'South Carolina'),
                ('South_Dakota', 'South Dakota'), ('Tennessee', 'Tennessee'), ('Texas', 'Texas'), ('Utah', 'Utah'),
                ('Vermont', 'Vermont'), ('Virginia', 'Virginia'), ('Washington', 'Washington'), ('West_Virginia', 'West Virginia'),
                ('Wisconsin', 'Wisconsin'), ('Wyoming', 'Wyoming')]
    state = forms.CharField(widget=forms.Select(choices=state_list, 
                            attrs={'placeholder': 'State', 'class': 'form-control', 
                                   'style': 'width : 160px; height: 40px'}))

    heredity_choices = [(1, "Yes"), (0, "No")]
    heredity = forms.ChoiceField(label='Do you have history of heart disease in your family?', choices=heredity_choices, 
                                 widget = forms.RadioSelect(attrs = {"class": "inline"}))

    smoke_choices = [(1, "Yes"), (0, "No")]
    smoke = forms.ChoiceField(label='Do you smoke regularly?', choices=smoke_choices, 
                              widget = forms.RadioSelect(attrs = {"class": "inline"}))

    active_choices = [(1, "Yes"), (0, "No")]
    active = forms.ChoiceField(label='Do you exercise regularly (>30 mins per day)?', choices=active_choices, 
                               widget = forms.RadioSelect(attrs = {"class": "inline"}))

    pre_existing_choices = [(1, "Yes"), (0, "No")]
    pre_existing = forms.ChoiceField(label='Do you have a pre-existing heart condition?', choices=pre_existing_choices, 
                                    widget = forms.RadioSelect(attrs = {"class": "inline"}))
    

    literacy_list = [('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('High', 'High')]
    literacy = forms.CharField(label='Literacy Level', widget=forms.Select(choices=literacy_list, 
                            attrs={'class': 'form-control', 'style': 'width : 160px; height: 40px'}))
    
        
    
    

heart_health/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from django import forms
from .forms import SurveyForm
from datetime import date
import risk_calculator
import econ_model
import pubmedcrawler
import googlescholarcrawler
import mayocliniccrawler
import webmdcrawler
import state_map
from django.template import RequestContext
from flask import Flask, render_template, request
import pickle
import numpy as np
import pandas as pd
from statsmodels.stats.proportion import proportions_ztest #pip install statsmodels in order to run this

'''
Renders views for the web pages and loads, stores, and modifies the user's data from 
the form in the dictionary 'cd', which stands for 'cleaned data'
'''


def survey(request):
    if request.method == 'POST':
        form = SurveyForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            
            weight = float(cd['weight']) * 0.453592 #converts weight from pounds to kgs
            height = float(cd['height']) * 0.3048 #converts height from feet to meters
            BMI =  round(weight / (height)**2, 2)
            cd['BMI'] = BMI
            cd.save()
            return render(request, 'heart_health/outcome.html', cd)
    else:
        form = SurveyForm()
    return render(request, 'heart_health/survey.html', {'form': form})
    

def index(request):
    return render(request, 'heart_health/index.html')


def outcome(request):
    if request.method == 'POST':
        form = SurveyForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            
            weight = float(cd['weight']) * 0.453592 #converts weight from pounds to kgs
            height = float(cd['height']) * 0.3048 #converts height from feet to meters
            BMI =  round(weight / (height)**2, 2)            
            cd['BMI'] = BMI

            age = (date.today() - cd['birth_date']).days
            cd['age'] = age
            
            risk_factors = risk_calculator.get_risk_factors()
            cd['risk_score'] = risk_calculator.predicting_risk(risk_factors, cd['age'], cd['BMI'], cd['sys_bp'], cd['smoke'], cd['active'], cd['heredity'], cd['pre_existing'])

            cd['screening_rec'] = econ_model.optimal_screen_freq(cd['risk_score'], cd['age'])

            cd['BMI_rank'] = risk_calculator.rank_BMI(cd['BMI'])
            
            cd['risk_str'] = risk_calculator.get_risk_string(cd)

            #Getting each of the articles
            cd['article_list'] = pubmedcrawler.get_articles_and_abstracts(cd['sys_bp'], cd['sex'], cd['BMI'], cd['smoke'], cd['literacy'])
            cd['article1'] = cd['article_list'][0]
            cd['article2'] = cd['article_list'][1]
            cd['article3'] = cd['article_list'][2]
            cd['article4'] = cd['article_list'][3]
            cd['article5'] = cd['article_list'][4]

            cd['gs_links'] = googlescholarcrawler.google_scholar_links(cd['sys_bp'], cd['sex'], cd['BMI'], cd['smoke'])
            cd['mayo_links'] = mayocliniccrawler.links_from_search(cd['sys_bp'], cd['sex'], cd['BMI'], cd['smoke'])
            cd['webmd_links'] = webmdcrawler.links_from_search(cd['sys_bp'], cd['sex'], cd['BMI'], cd['smoke'])

            cd['href_state'], cd['img_src_state'] = state_map.get_img_src(cd['state'])
            cd['map_path'] = "heart_health/state_maps/" + cd['state'] + ".png" 
            cd['mortality'], cd['deaths'] = state_map.retrieve_stats_for_state(cd["state"])

            pickle.dump(cd, open('survey_data.pkl', 'wb'))
                
            return render(request, 'heart_health/outcome.html', cd)
    else:
        cd = pickle.load(open('survey_data.pkl', 'rb'))
        return render(request, 'heart_health/outcome.html', cd)

    
def education(request):
    cd = pickle.load(open('survey_data.pkl', 'rb'))
    cd['article_list'] = pubmedcrawler.get_articles_and_abstracts(cd['sys_bp'], cd['sex'], cd['BMI'], cd['smoke'], cd['literacy'])
    cd['article1'] = cd['article_list'][0]
    cd['article2'] = cd['article_list'][1]
    cd['article3'] = cd['article_list'][2]
    cd['article4'] = cd['article_list'][3]
    cd['article5'] = cd['article_list'][4] 

    pickle.dump(cd, open('survey_data.pkl', 'wb'))

    return render(request, 'heart_health/education.html', cd)

heart_health/templates/heart_health/education.html
<!DOCTYPE html>
<html>
<head>
<style>

.myDiv {
    border-radius: 25px;
    border: 2px solid #800000;
    padding: 20px;
    width: 80%;
    background-color: #f2f2f2;
}

.button {
  display: flex;
  justify-content: center;
  padding: 15px 25px;
  font-size: 20px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #800000;
  border: none;
  border-radius: 25px;
  box-shadow: 0 5px #999;
}

.button:hover {background-color: #fd6c6c}

.button:active {
  background-color: #fd6c6c;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}

.button1 {
    border-radius: 25px;
    margin:auto;
    width: 30%;
    text-align: center;
    border: 2px solid #800000;
    padding: 10px;
    background-color: #c44242;
}

</style>

</head>

<body>
    <br>
    <h1 style="text-align: center;">Educational Resources For You</h1><br>

    <div class="myDiv" style="margin:0 auto;">
        <h2>{{ article1.1 }}</h2>
        <p>{{article1.2}}</p>
        <a href={{article1.0}} style = "color:maroon; text-decoration: none;">Article Link</a>
        <p>
            {{article1.3}}
        </p>
        <p><i><b>Reading level: {{ article1.4 }}</b> (Reading score: {{ article1.5 }})</i></p>
      </div>
     <br>
     <br>

    <div class="myDiv" style="margin:0 auto;">
        <h2>{{ article2.1 }}</h2>
        <p>{{article2.2}}</p>
        <a href={{article2.0}} style = "color:maroon; text-decoration: none;">Article Link</a>
        <p>
            {{article2.3}}
        </p>
        <p><i><b>Reading level: {{ article2.4 }}</b> (Reading score: {{ article2.5 }})</i></p>
      </div>
     <br>
     <br>
    
    <div class="myDiv" style="margin:0 auto;">
        <h2>{{ article3.1 }}</h2>
        <p>{{article3.2}}</p>
        <a href={{article3.0}} style = "color:maroon; text-decoration: none;">Article Link</a>
        <p>
            {{article3.3}}
        </p>
        <p><i><b>Reading level: {{ article3.4 }}</b> (Reading score: {{ article3.5 }})</i></p>
      </div>
     <br>
     <br>
    
    <div class="myDiv" style="margin:0 auto;">
        <h2>{{ article4.1 }}</h2>
        <p>{{article4.2}}</p>
        <a href={{article4.0}} style = "color:maroon; text-decoration: none;">Article Link</a>
        <p>
            {{article4.3}}
        </p>
        <p><i><b>Reading level: {{ article4.4 }}</b> (Reading score: {{ article4.5 }})</i></p>
      </div>
     <br>
     <br>
    
    <div class="myDiv" style="margin:0 auto;">
        <h2>{{ article5.1 }}</h2>
        <p>{{article5.2}}</p>
        <a href={{article5.0}} style = "color:maroon; text-decoration: none;">Article Link</a>
        <p>
            {{article5.3}}
        </p>
        <p><i><b>Reading level: {{ article5.4 }}</b> (Reading score: {{ article5.5 }})</i></p>
      </div>
     <br>
     <br>
    
    <div class="myDiv" style="margin:0 auto;">
        <h2>Further reading:</h2>
        <ul style="font-size: medium;">
            <li><a href={{gs_links.0}} style = "color:maroon">{{gs_links.0}}</a></li>
            <li><a href={{mayo_links.0}} style = "color:maroon">{{mayo_links.0}}</a></li>
            <li><a href={{webmd_links.0}} style = "color:maroon">{{webmd_links.0}}</a></li>
            <li><a href={{gs_links.1}} style = "color:maroon">{{gs_links.1}}</a></li>
            <li><a href={{mayo_links.1}} style = "color:maroon">{{mayo_links.1}}</a></li>
            <li><a href={{webmd_links.1}} style = "color:maroon">{{webmd_links.1}}</a></li>
            <li><a href={{gs_links.2}} style = "color:maroon">{{gs_links.2}}</a></li>
            <li><a href={{mayo_links.2}} style = "color:maroon">{{mayo_links.2}}</a></li>
            <li><a href={{webmd_links.2}} style = "color:maroon">{{webmd_links.2}}</a></li>
            <li><a href={{gs_links.3}} style = "color:maroon">{{gs_links.3}}</a></li>
        </ul> 
      </div>
     <br>
     <br>

<button class="button" style="margin:0 auto; color:white" type="button">
    <a href="{% url 'heart_health:outcome' %}" style = "color:white; text-decoration: none;">Back</a>
</button>
<br>
<br>

</body>
</html>

heart_health/templates/heart_health/index.html
<!DOCTYPE html>
<html>
<head>
<style>

.myDiv {
    border-radius: 25px;
    border: 2px solid #800000;
    padding: 20px;
    width: 80%;
    background-color: #f2f2f2;
    animation: fadeInAnimation ease 3s;
    animation-iteration-count: 1;
    animation-fill-mode: forwards;
}

/*
body {
    animation: fadeInAnimation ease 3s;
    animation-iteration-count: 1;
    animation-fill-mode: forwards;
}
*/

@keyframes fadeInAnimation {
    0% {
        opacity: 0;
    }
    100% {
        opacity: 1;
     }
}


.button {
  display: flex;
  justify-content: center;
  padding: 15px 25px;
  font-size: 21px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #800000;
  border: none;
  border-radius: 25px;
  box-shadow: 0 9px #999;
}

.button:hover {background-color: #fd6c6c}

.button:active {
  background-color: #fd6c6c;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}

.button1 {
    border-radius: 25px;
    margin:auto;
    width: 30%;
    text-align: center;
    border: 2px solid #800000;
    padding: 10px;
    background-color: #c44242;
}

</style>

</head>

<body>
    <br>
    <h1 style="text-align: center;">Learn About Your Cardiovascular Health!</h1><br>

    <div class="myDiv" style="margin:0 auto;">
        <h2>You will discover:</h2>
        <ul style="font-size: large;">
            <li>Your <b>risk score</b> for heart disease based on a random 
                forest machine learning algorithm trained and tested on a 
                dataset of 70,000 people and statistical 2-proportion z 
                testing for risk factors</li>
            <br>
            <li><b>Cardiovascular screening frequency recommendations</b> 
                based on your personal risk for severe heart disease and a
                cost benefit economic model</li>
            <br>
            <li>Your <b>geographic risk</b> based on your state's deaths
                from cardiovascular disease as compared to other states</li>
            <br>
            <li><b>Educational articles</b> from PubMed, WebMD, and Google 
                Scholar personally curated to your risk for cardiovascular
                disease, related risk factors, location, and literacy level
                (using natural language processing)</li>
        </ul>
    
      </div>
     <br>
     <br>

<button class="button" style="margin:0 auto; color:white" type="button">
    <a href="{% url 'heart_health:survey' %}" style = "color:white; text-decoration: none;">Take Survey!</a>
</button>

</body>
</html>

heart_health/templates/heart_health/outcome.html
{%load static %}
<!DOCTYPE html>
<html>
<head>
<style>

.wrapper {
    display: flex;
    gap: 12px;
    align-items: center;
    justify-content: center;
    padding: 10px;
}

.wrapper > div {
    flex: 1;
}

.myDiv {
    border-radius: 25px;
    border: 2px solid #800000;
    padding: 20px;
    width: 80%;
    background-color: #f2f2f2;
    justify-self: center;
    flex: 1;
}

.columns {
  column-count: 2;
  column-gap: 40px;
  border-radius: 25px;
  border: 2px solid #800000;
  padding: 10px;
  background-color: #f2f2f2;
}

.button {
  display: flex;
  justify-content: center;
  padding: 15px 25px;
  font-size: 21px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #800000;
  border: none;
  border-radius: 25px;
  box-shadow: 0 5px #999;
}

.button:hover {background-color: #fd6c6c}

.button:active {
  background-color: #fd6c6c;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}

.button1 {
    border-radius: 25px;
    margin:auto;
    width: 30%;
    text-align: center;
    border: 2px solid #800000;
    padding: 10px;
    background-color: #c44242;
}

</style>

</head>
<body>

<br>
<h1 style="text-align: center;">Hi, {{ name }}!</h1>

<br>

<div class="wrapper">
    <div class="myDiv">
        <h2>Your Risk Score: {{ risk_score }} </h2>
        <p>More information: </p>
        <ul>
            <li>Your BMI is <b>{{ BMI }}</b>, which is in the <b>{{BMI_rank}}</b> category.</li>
            <br>
            <li>{{ risk_str }}</li>
        </ul>
    </div>
    <div class="myDiv">
        <h2>Screening Recommendation: {{ screening_rec }} </h2>
        <ul>
        <li>Screening for heart disease is commonly done using a CT scan, an exercise stress test, or an EKG. </li>
        <br>
        <li>The average cost of screening for heart disease is approximately $400 or less.</li>
        <br>
        <li>The average cost of treatment for severe heart disease for hospital stay and follow-up care can be $35,000 and up.</li>
        </ul>
    </div>
</div>

<br>
<br>
<div class="myDiv" style="margin:0 auto;">
    <p style="text-align: center; font-size: 20px;">
        You live in a state with a mortality rate of <b>{{ mortality }}</b> deaths per 100,000 people per year.
    </p>
    <br>
    <p style="text-align: center;">
        <img src="/static/{{ map_path }}" width="600">
    </p>
</div>
<br>
<br>
<div class="myDiv" style="margin:0 auto;">
    <button class="button" style="margin:0 auto; color:white" type="button">
        <a href="{% url 'heart_health:education' %}" 
        style = "color:white; text-decoration: none;">Your Educational 
        Guide To Heart Disease</a>
    </button>
    <br>
    <p style="text-align: center; font-size: 18px;">
        Find your curated guide with personalized article recommendations
        based on your reading level and risk factors from scholarly sources.
    </p>
    <p style = "color:maroon; text-align: center">
        Knowledge is power so it's worth the wait :) (Again, this may take 30 seconds)
    </p>
</div>
<br>
<br>
<div class="myDiv" style="margin:0 auto;">
    <p style="font-size: 18px;">
        How was your risk score determined?
    </p>
    <ul style="font-size: medium;">
        <li>Your risk score was determined based on a random 
            forest machine learning algorithm trained and tested on a 
            dataset of 70,000 people. The output of this machine learning algorithm
            was then combined with a weighted points system that determined risk 
            factors via 2-proportion z testing.</li>
            </ul>
    <p style="font-size: 18px;">
        How was your screening recommendation determined?
    </p>
    <ul style="font-size: medium;">
        <li>Your screening recommendation frequency was determined via an 
            economic model that weighed the cost of screening for your lifetime
            versus the weighted cost of severe heart disease (ultimately leading to
            a heart attack).
        </li>

</div>
<br>
<br>

</body>
</html>

heart_health/templates/heart_health/survey.html
<!DOCTYPE html>
<html>
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">

<style>

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: maroon;
  color: white;
  padding: 15px 25px;
  border: none;
  border-radius: 25px;
  display: flex;
  justify-content: center;
  cursor: pointer;
  box-shadow: 0 5px #999;
  font-size: 18px;
}

input[type=submit]:hover {
  background-color: #fd6c6c;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}

.myDiv {
    border-radius: 25px;
    border: 2px solid #800000;
    padding: 20px;
    width: 65%;
    background-color: #f2f2f2;
}

.button {
  display: flex;
  justify-content: center;
  padding: 15px 25px;
  font-size: 21px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #800000;
  border: none;
  border-radius: 25px;
  box-shadow: 0 9px #999;
}

.button:hover {background-color: #fd6c6c}

.button:active {
  background-color: #fd6c6c;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}

.button1 {
    border-radius: 25px;
    margin:auto;
    width: 30%;
    text-align: center;
    border: 2px solid #800000;
    padding: 10px;
    background-color: #c44242;
}

</style>

</head>
<body>
<br>
<h1 style="text-align: center;">Cardiovascular Health Survey</h1><br>
<div class="myDiv" style="margin:0 auto;">
    <form name = 'SurveyForm' action="{% url 'heart_health:outcome' %}" method="post" id="SurveyForm">
      {% csrf_token %}
      {{ form.as_p }}
      <br>

      <button class = "button" type="submit" value="Submit" style="margin:0 auto; color:white">Submit</button>

    </form>
    <br>
    <p style="color:maroon; text-align: center">Sit back, relax, and sip some tea :) Let the computer do the heavy lifting!</p>
    <p style="color:maroon; text-align: center">(This may take 30 seconds to a minute)</p>
  </div>

<br>
<br>
</body>
</html>